version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tarefas_db
    environment:
      POSTGRES_USER: toine97
      POSTGRES_PASSWORD: projeto123
      POSTGRES_DB: tarefas_casa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: